[package]
name = "coreutils_module"
license = "MIT"
version = "0.2.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "Small building block for modularized applications."

[dependencies]
log = "0.4"

[dev-dependencies]
lazy_static = "1.0"