[package]
name = "coreutils_logger"
license = "MIT"
version = "0.2.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "Logger configuration based on fern."

[dependencies]
chrono = "0.4"
fern = "0.5"
log = "0.4"
